### ISSUE TITLE
Server can't quit

### ISSUE THREAD

**Issue by bearda** [ahwmrklas/warpWarp#15]
Title says it all. We get a stupid error every time we try to quit. its wreaking havoc on my ability to write unit tests.

```
Exception in thread ServerSvrThread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/bearda/proj/warpWarp/server.py", line 61, in run
    cmd = zlib.decompress(compressed)
zlib.error: Error -3 while decompressing data: incorrect header check

```

We are trying to send information that we didn't compress. I can't figure out where. I think it has to do with the server's quit command using a different type of connection than everyone else.

**Comment by bearda** [comment]
All I had to do is compress the quit command
